# Generated by Django 4.2.5 on 2023-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
